- .github/workflows/ci.yml
- custom_google_checks.xml
> feat: github Actions CI 설정

- .github/workflows/ci.yml
> chore: ci 빌드 테스트 재시도

- .github/workflows/ci.yml
release 브랜치 체크 스타일 변경
어떤 변경 사항이 있나요?
> chore: release 브랜치 체크 스타일 변경

- .github/workflows/cd-develop.yml
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/InfoResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/SaveRequest.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestEntity.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestService.java
- src/main/resources/application.yml
> Feature/24 배포 파이프라인 테스트

- .github/workflows/cd-develop.yml
> docs: 배포 cicd 폴더 생성

- .github/workflows/cd-develop.yml
배포 cicd 폴더 생성 수정
어떤 변경 사항이 있나요?
> docs: 배포 cicd 폴더 생성 수정

- src/main/java/kr/co/fastcampus/fastcatch/domain/test/TestService.java
저장 메소드 @transactional 수정
어떤 변경 사항이 있나요?
> fix: 저장 메소드 @transactional 수정

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/request/AccommodationSaveRequest.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationInfoResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
숙박엔티티에 전화번호, 위도 경도 추가
개별 숙박 상세조회시 전화번호 위도, 경도 추가
어떤 변경 사항이 있나요?
> feat: 숙박엔티티에 전화번호, 위도 경도 추가

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
대소문자 구분이 가능하여 안되는 것으로 판단하고 Room room으로 변경
어떤 변경 사항이 있나요?
> fix: 테스트 서버 MySQL 에서 Room 테이블 인식못하는 버그

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationOptionResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomOptionResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/AccommodationOption.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/RoomOption.java
fix: 테스트 서버 MySQL 에서 boolean : is prefix 생기는 버그
어떤 변경 사항이 있나요?
> fix: 테스트 서버 MySQL 에서 boolean : is prefix 생기는 버그

- .github/workflows/cd-release.yml
release 브랜치 자동배포 파이프라인 구축 오타 수정
어떤 변경 사항이 있나요?
> chore: release 브랜치 자동배포 파이프라인 구축 오타 수정

- .github/workflows/cd-release.yml
release 브랜치 자동배포 파이프라인 구축 오타 수정
어떤 변경 사항이 있나요?
> release 브랜치 자동배포 파이프라인 구축 오타 수정

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
숙박데이터 , 옵션들 리스트로 한번에 받아서 저장할 수 있도록 api 작성
어떤 변경 사항이 있나요?
> Feature/48 숙박데이터 , 옵션들 리스트로 한번에 받아서 저장할 수 있도록 api 작성

- .github/workflows/cd-release.yml
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/RoomResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
숙박과 옵션들 리스트로 한번에 저장할 수 있는 API 작성 
어떤 변경 사항이 있나요?
> Develop refactor: 숙박과 옵션들 리스트로 한번에 저장할 수 있는 API 작성 

- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
fix: 프론트 연결시 CORS 에러 문제 해결
어떤 변경 사항이 있나요?
> fix: 프론트 연결시 CORS 에러 문제 해결

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/select/cart-getAll-byMemberId.http
> fix: readOnly 삭제

- src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/repository/MemberRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
닉네임 조회 API 명세서에 맞게 수정
어떤 변경 사항이 있나요?
> fix: 닉네임 조회 API 명세서에 맞게 수정

- src/main/resources/application.yml
비밀번호 오류시 클라이언트에게 전송 못하게 막음
어떤 변경 사항이 있나요?
> fix: 비밀번호 오류시 클라이언트에게 전송 못하게 막음

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSummaryResponse.java
숙박 전체 조회시 주소 추가
어떤 변경 사항이 있나요?
> fix: 숙박 전체 조회시 주소 추가

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemListResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
장바구니 조회시 호텔끼리 묶어서 나타나게 변경
어떤 변경 사항이 있나요?
> fix: 장바구니 조회시 호텔끼리 묶어서 나타나게 변경

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
> chore: 장바구니 롤백

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteAll.http
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteItem-byCartItemId.http
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/select/cart-getAll-byMemberId.http
이건 바로 develop으로 보내서 프론트에서 동작할 수 있도록 할 예정입니다
그래서 restful 하지 않지만 동작은 하는 url입니다
어떤 변경 사항이 있나요?
> [Fix] 카트 동작은 하는데 restful 하지 않음

- src/test/java/kr/co/fastcampus/fastcatch/common/ApiTest.java
- src/test/java/kr/co/fastcampus/fastcatch/common/DatabaseCleaner.java
- src/test/java/kr/co/fastcampus/fastcatch/common/DatabaseClearExtension.java
- src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
- src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationControllerTest.java
- src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationServiceTest.java
> Feature/69 테스트 코드 틀 작성

- src/main/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/order/service/OrderService.java
프론트측 요청사항 변경으로 주문 생성 시, 응답 데이터에 생성된 주문 정보 추가하였습니다. 
요청한 정보는 주문 ID였고 혹시 몰라서 주문 데이터 전부 보내도록 구현하였습니다. 
어떤 변경 사항이 있나요?
> Feature/72 주문 생성 (즉시&장바구니) API 응답 DTO 추가 구현

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemListResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartItemResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/insert/cart-insertItem.http
장바구니 아이템의 룸을 숙박으로 묶는 Dto와 서비스 코드를 추가했습니다.
지금은 생성 쪽에만 적용했고, 삭제는 아직 안 만들었는데 프론트 테스트를 위해 올립니다.
어떤 변경 사항이 있나요?
> [Feature]프론트 요구에 맞게 장바구니 기능 변경

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/dto/response/CartResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/service/CartService.java
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteAll.http
- src/test/java/kr/co/fastcampus/fastcatch/http_test/cart/delete/cart-deleteItem-byCartItemId.http
장바구니 조회 기능에도 적용했습니다.
어떤 변경 사항이 있나요?
> [Feature] 프론트 기능에 맞춘 장바구니

- src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/controller/AccommodationControllerTest.java
- src/test/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationServiceTest.java
숙박 도메인 API 테스트 코드를 작성하였습니다.
어떤 변경 사항이 있나요?
> Feature/69 숙박 도메인 API 테스트 코드를 작성

- src/main/java/kr/co/fastcampus/fastcatch/domain/cart/controller/CartController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/order/controller/OrderController.java
> chore: import 문 순서 변경

- src/main/java/kr/co/fastcampus/fastcatch/common/config/SecurityConfig.java
회원가입 과정에서 필요한 API이므로 인증없이 접근가능하도록 허용 필요
따라서 해당 API 경로 permitAll 설정 추가
어떤 변경 사항이 있나요?
> Feature/84 닉네임 조회 API 접근권한 변경

- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
> refactor: cors 설정 변경

- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
> Feature/80 cors 설정 변경

- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
> refactor: cors 설정

- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationPageResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/dto/response/AccommodationSearchPageResponse.java
> Feature/80 cors 전체 공개로 수정

- src/main/java/kr/co/fastcampus/fastcatch/common/config/SecurityConfig.java
- src/main/java/kr/co/fastcampus/fastcatch/common/config/WebConfig.java
> fix: cors 설정 변경

- src/test/java/kr/co/fastcampus/fastcatch/common/MemberTokenUtil.java
- src/test/java/kr/co/fastcampus/fastcatch/common/TestUtil.java
- src/test/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberControllerTest.java
- src/test/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberServiceTest.java
멤버 도메인 테스트 코드 작성
어떤 변경 사항이 있나요?
> test: 멤버 도메인 테스트 코드 작성

- src/main/java/kr/co/fastcampus/fastcatch/common/config/SecurityConfig.java
- src/main/java/kr/co/fastcampus/fastcatch/common/exception/TokenNotMatchedException.java
- src/main/java/kr/co/fastcampus/fastcatch/common/response/ErrorCode.java
- src/main/java/kr/co/fastcampus/fastcatch/common/security/jwt/JwtAuthenticationFilter.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/controller/MemberController.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/request/MemberSignOutRequest.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/dto/response/MemberSignOutResponse.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/entity/BlackList.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/repository/BlackListRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/BlackListService.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/member/service/MemberService.java
- src/main/resources/application.yml
- 현재 DB에 BlackList 테이블 추가 
- 로그아웃 API 요청 시, 회원이메일, 액세스토큰, 리프레시 토큰 저장하도록 구현 
- 로그인 필요한 기능에 전달되는 액세스토큰이 블랙리스트에 있는지 확인하는 검증 작업 추가 
- MemberService에 블랙리스트 관련 메서드 구현하다가, MemberService<->SecurityConfig 순환참조 발생하여 따로 분리하여 구현함 
- 토큰 재발급 API merge 후에 JwtExceptionFilter 적용해서 로그아웃 후 로그인필요한 기능 예외처리 잘 되는지 확인
- 리프레시 토큰 재발급 시 리프레시 토큰이 블랙리스트에 있는지 확인하는 로직 추가
**로그아웃 성공**
**블랙리스트 DB에 생성 확인**
**리프레시 토큰 재발급 실패(로그아웃 회원 = 블랙리스트에 있는 리프레시 토큰으로 요청함)**
**로그인이 필요한 기능 실패 (로그아웃)**
어떤 변경 사항이 있나요?
> Feature/125 임시 로그아웃 API 구현

- .github/workflows/cd-develop.yml
테스트 서버 종료로 인한 develop브랜치 cd.yml 주석
어떤 변경 사항이 있나요?
> ci: 테스트 서버 종료로 인한 develop브랜치 cd.yml 주석

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/AccommodationRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
인덱스 사용을 위한 where 절 조건 순서 변경
어떤 변경 사항이 있나요?
> 인덱스 사용을 위한 where 절 조건 순서 변경

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/AccommodationRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
where절 조건 순서 다시 변경
어떤 변경 사항이 있나요?
> where절 조건 순서 다시 변경

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Room.java
accommodation 엔티티에 category, region 복합 인덱스 설정
room 엔티티에 accommodation_id 인덱스 설정
어떤 변경 사항이 있나요?
> 숙박 도메인 accommodation 엔티티, room 엔티티 인덱스 설정

- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/entity/Accommodation.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/repository/AccommodationRepository.java
- src/main/java/kr/co/fastcampus/fastcatch/domain/accommodation/service/AccommodationService.java
category, region 복합인덱스에서 성능을 위해 Cardinality 가 높은 region이 category 보다 앞서서 오도록 인덱스 수정
어떤 변경 사항이 있나요?
> 성능을 위해 Cardinality 가 높은 region이 복합 인덱스 앞에 오도록 수정
